[build]
  # Base directory where the project files are located
  base = "promohive"
  
  # Build command
  command = "npm install && npm run build"
  
  # Output directory (relative to base)
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Redirects for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
